theme: jekyll-theme-minimal
title: Upcoming Events in Harmonic Analysis
email: jdedios@math.ucla.edu
description: >- # this means to ignore newlines
  List of upcoming events tangentially related to analysis and related topics (with a weak and somewhat opinionated definition of *related*). Email me if you think there's an event that could be here!
  
twitter_username: jaumededios
github_username:  jaumededios
